const datas = [
	{
		_id: { $oid: "6786515b0fd9afe1b707ccef" },
		name: "Keychron K2",
		category: "Keyboard",
		brand: "Keychron",
		layout: "75%",
		caseMaterial: "Aluminum",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: true,
		switchType: "Mechanical Switch",
		rappodTrigger: false,
		tags: ["Keyboard", "RGB Backlit", "Hotswap"],
		price: 89.99,
		model: "K2",
		series: "K",
		stock: 100,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707ccf0" },
		name: "Akko 3098S One Piece RGB",
		category: "Keyboard",
		brand: "Akko",
		layout: "96%",
		caseMaterial: "Walnut Wood",
		collabTheme: "One Piece",
		rgbBacklit: true,
		hotswap: true,
		switchType: "Mechanical Switch",
		rappodTrigger: true,
		tags: ["Keyboard", "RGB Backlit", "Hotswap", "Rappid Trigger", "Multi-Mode"],
		price: 129.99,
		model: "3098S",
		series: "Tokyo",
		stock: 50,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707ccf1" },
		name: "Anne Pro 2",
		category: "Keyboard",
		brand: "Anne Pro",
		layout: "60%",
		caseMaterial: "Plastic",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: true,
		switchType: "Mechanical Switch",
		rappodTrigger: true,
		tags: ["Keyboard", "RGB Backlit", "Hotswap", "Rappid Trigger"],
		price: 89.99,
		model: "Pro 2",
		series: "Pro",
		stock: 90,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707ccf2" },
		name: "Razer Huntsman Mini",
		category: "Keyboard",
		brand: "Razer",
		layout: "60%",
		caseMaterial: "Plastic",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: false,
		switchType: "Optical Switch",
		rappodTrigger: true,
		tags: ["Keyboard", "RGB Backlit", "Rappid Trigger"],
		price: 119.99,
		model: "Huntsman Mini",
		series: "Huntsman",
		stock: 80,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707ccf3" },
		name: "SteelSeries Apex Pro",
		category: "Keyboard",
		brand: "SteelSeries",
		layout: "Fullsize",
		caseMaterial: "Aluminum",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: false,
		switchType: "Mechanical Switch",
		rappodTrigger: true,
		tags: ["Keyboard", "RGB Backlit", "Rappid Trigger"],
		price: 199.99,
		model: "Apex Pro",
		series: "Apex",
		stock: 30,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707ccf4" },
		name: "Corsair K95 RGB Platinum",
		category: "Keyboard",
		brand: "Corsair",
		layout: "Fullsize",
		caseMaterial: "Aluminum",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: false,
		switchType: "Mechanical Switch",
		rappodTrigger: true,
		tags: ["Keyboard", "RGB Backlit", "Rappid Trigger"],
		price: 199.99,
		model: "K95",
		series: "K",
		stock: 40,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707ccf5" },
		name: "Logitech G Pro X",
		category: "Keyboard",
		brand: "Logitech",
		layout: "Tenkeyless",
		caseMaterial: "Plastic",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: true,
		switchType: "Mechanical Switch",
		rappodTrigger: true,
		tags: ["Keyboard", "RGB Backlit", "Hotswap", "Rappid Trigger"],
		price: 149.99,
		model: "G Pro X",
		series: "G",
		stock: 75,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707ccf6" },
		name: "Varmilo VA87M",
		category: "Keyboard",
		brand: "Varmilo",
		layout: "Tenkeyless",
		caseMaterial: "Plastic",
		collabTheme: null,
		rgbBacklit: false,
		hotswap: false,
		switchType: "Mechanical Switch",
		rappodTrigger: false,
		tags: ["Keyboard"],
		price: 139.99,
		model: "VA87M",
		series: "VA",
		stock: 50,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707ccf7" },
		name: "Ducky One 2 Mini",
		category: "Keyboard",
		brand: "Ducky",
		layout: "60%",
		caseMaterial: "Plastic",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: false,
		switchType: "Mechanical Switch",
		rappodTrigger: true,
		tags: ["Keyboard", "RGB Backlit", "Rappid Trigger"],
		price: 109.99,
		model: "One 2 Mini",
		series: "One",
		stock: 60,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707ccf8" },
		name: "Leopold FC660M",
		category: "Keyboard",
		brand: "Leopold",
		layout: "65%",
		caseMaterial: "Plastic",
		collabTheme: null,
		rgbBacklit: false,
		hotswap: false,
		switchType: "Mechanical Switch",
		rappodTrigger: false,
		tags: ["Keyboard"],
		price: 119.99,
		model: "FC660M",
		series: "FC",
		stock: 70,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707ccf9" },
		name: "GMMK Pro",
		category: "Keyboard",
		brand: "Glorious",
		layout: "75%",
		caseMaterial: "Aluminum",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: true,
		switchType: "Mechanical Switch",
		rappodTrigger: true,
		tags: ["Keyboard", "RGB Backlit", "Hotswap", "Rappid Trigger"],
		price: 169.99,
		model: "Pro",
		series: "GMMK",
		stock: 45,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707ccfa" },
		name: "NuPhy Air75",
		category: "Keyboard",
		brand: "NuPhy",
		layout: "75%",
		caseMaterial: "Aluminum",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: true,
		switchType: "Low Profile Switch",
		rappodTrigger: true,
		tags: ["Keyboard", "RGB Backlit", "Hotswap", "Low Profile"],
		price: 129.99,
		model: "Air75",
		series: "Air",
		stock: 55,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707ccfb" },
		name: "Drop CTRL",
		category: "Keyboard",
		brand: "Drop",
		layout: "Tenkeyless",
		caseMaterial: "Aluminum",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: true,
		switchType: "Mechanical Switch",
		rappodTrigger: true,
		tags: ["Keyboard", "RGB Backlit", "Hotswap", "Rappid Trigger"],
		price: 199.99,
		model: "CTRL",
		series: "Drop",
		stock: 35,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707ccfc" },
		name: "Royal Kludge RK84",
		category: "Keyboard",
		brand: "Royal Kludge",
		layout: "75%",
		caseMaterial: "Plastic",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: true,
		switchType: "Mechanical Switch",
		rappodTrigger: false,
		tags: ["Keyboard", "RGB Backlit", "Hotswap"],
		price: 79.99,
		model: "RK84",
		series: "RK",
		stock: 85,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707ccfd" },
		name: "Epomaker TH80",
		category: "Keyboard",
		brand: "Epomaker",
		layout: "75%",
		caseMaterial: "Plastic",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: true,
		switchType: "Mechanical Switch",
		rappodTrigger: false,
		tags: ["Keyboard", "RGB Backlit", "Hotswap"],
		price: 89.99,
		model: "TH80",
		series: "TH",
		stock: 65,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707ccfe" },
		name: "Ducky One 3",
		category: "Keyboard",
		brand: "Ducky",
		layout: "Fullsize",
		caseMaterial: "Plastic",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: true,
		switchType: "Mechanical Switch",
		rappodTrigger: true,
		tags: ["Keyboard", "RGB Backlit", "Hotswap", "Rappid Trigger"],
		price: 129.99,
		model: "One 3",
		series: "One",
		stock: 40,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707ccff" },
		name: "Akko 3068B Plus",
		category: "Keyboard",
		brand: "Akko",
		layout: "65%",
		caseMaterial: "Plastic",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: true,
		switchType: "Mechanical Switch",
		rappodTrigger: true,
		tags: ["Keyboard", "RGB Backlit", "Hotswap", "Rappid Trigger"],
		price: 99.99,
		model: "3068B Plus",
		series: "Plus",
		stock: 75,
		currency: "USD",
		src: "https://th.bing.com/th/id/OIP.wEMH1MzDS6_qlag0y4zQ8gHaHa?rs=1&pid=ImgDetMain",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707cd00" },
		name: "KBDfans D84",
		category: "Keyboard",
		brand: "KBDfans",
		layout: "75%",
		caseMaterial: "Aluminum",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: true,
		switchType: "Mechanical Switch",
		rappodTrigger: false,
		tags: ["Keyboard", "RGB Backlit", "Hotswap"],
		price: 299.99,
		model: "D84",
		series: "D",
		stock: 25,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707cd01" },
		name: "Zoom65",
		category: "Keyboard",
		brand: "Meletrix",
		layout: "65%",
		caseMaterial: "Aluminum",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: true,
		switchType: "Mechanical Switch",
		rappodTrigger: false,
		tags: ["Keyboard", "RGB Backlit", "Hotswap"],
		price: 179.99,
		model: "Zoom65",
		series: "Zoom",
		stock: 30,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707cd02" },
		name: "Keydous NJ80",
		category: "Keyboard",
		brand: "Keydous",
		layout: "75%",
		caseMaterial: "Plastic",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: true,
		switchType: "Mechanical Switch",
		rappodTrigger: false,
		tags: ["Keyboard", "RGB Backlit", "Hotswap"],
		price: 119.99,
		model: "NJ80",
		series: "NJ",
		stock: 60,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707cd03" },
		name: "Mode Sonnet",
		category: "Keyboard",
		brand: "Mode",
		layout: "75%",
		caseMaterial: "Aluminum",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: true,
		switchType: "Mechanical Switch",
		rappodTrigger: false,
		tags: ["Keyboard", "RGB Backlit", "Hotswap"],
		price: 299.99,
		model: "Sonnet",
		series: "Mode",
		stock: 20,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707cd04" },
		name: "Owlab Spring",
		category: "Keyboard",
		brand: "Owlab",
		layout: "75%",
		caseMaterial: "Aluminum",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: true,
		switchType: "Mechanical Switch",
		rappodTrigger: false,
		tags: ["Keyboard", "RGB Backlit", "Hotswap"],
		price: 389.99,
		model: "Spring",
		series: "Owlab",
		stock: 15,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707cd05" },
		name: "QK65",
		category: "Keyboard",
		brand: "QwertyKeys",
		layout: "65%",
		caseMaterial: "Aluminum",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: true,
		switchType: "Mechanical Switch",
		rappodTrigger: false,
		tags: ["Keyboard", "RGB Backlit", "Hotswap"],
		price: 249.99,
		model: "QK65",
		series: "QK",
		stock: 25,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707cd06" },
		name: "Feker IK75",
		category: "Keyboard",
		brand: "Feker",
		layout: "75%",
		caseMaterial: "Plastic",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: true,
		switchType: "Mechanical Switch",
		rappodTrigger: false,
		tags: ["Keyboard", "RGB Backlit", "Hotswap"],
		price: 69.99,
		model: "IK75",
		series: "IK",
		stock: 95,
		currency: "USD",
	},
	{
		_id: { $oid: "6786515b0fd9afe1b707cd07" },
		name: "Monokei Standard",
		category: "Keyboard",
		brand: "Monokei",
		layout: "60%",
		caseMaterial: "Aluminum",
		collabTheme: null,
		rgbBacklit: true,
		hotswap: true,
		switchType: "Mechanical Switch",
		rappodTrigger: false,
		tags: ["Keyboard", "RGB Backlit", "Hotswap"],
		price: 279.99,
		model: "Standard",
		series: "Monokei",
		stock: 20,
		currency: "USD",
	},
	{
		_id: { $oid: "678fff12b131ed622ef22d80" },
		name: "Keychron K6",
		category: "Keyboard",
		brand: "Keychron",
		layout: "65%",
		caseMaterial: "Aluminum",
		collabTheme: "Anime",
		rgbBacklit: true,
		hotswap: true,
		switchType: "Gateron",
		rappodTrigger: false,
		tags: ["Custom", "RGB Backlit"],
		price: 89.99,
		model: "K6",
		series: "K",
		stock: 100,
		currency: "USD",
	},
	{
		_id: { $oid: "678fff12b131ed622ef22d84" },
		name: "Akko 3068",
		category: "Keyboard",
		brand: "Akko",
		layout: "75%",
		caseMaterial: "Acrylic",
		collabTheme: "Music",
		rgbBacklit: true,
		hotswap: true,
		switchType: "Kailh",
		rappodTrigger: false,
		tags: ["Customizable", "RGB Backlit"],
		price: 99.99,
		model: "3068",
		series: "306",
		stock: 70,
		currency: "USD",
		src: "https://the-gadgeteer.com/wp-content/uploads/2021/02/akko3068_01.jpg",
	},
	{
		_id: { $oid: "678fff12b131ed622ef22d85" },
		name: "Vortex Pok3r",
		category: "Keyboard",
		brand: "Vortex",
		layout: "60%",
		caseMaterial: "Metal",
		collabTheme: "Anime",
		rgbBacklit: false,
		hotswap: false,
		switchType: "Cherry MX",
		rappodTrigger: false,
		tags: ["Custom", "Vintage"],
		price: 119.99,
		model: "Pok3r",
		series: "Pok",
		stock: 20,
		currency: "USD",
	},
	{
		_id: { $oid: "678fff12b131ed622ef22d87" },
		name: "Filco Majestouch 2",
		category: "Keyboard",
		brand: "Filco",
		layout: "Fullsize",
		caseMaterial: "Metal",
		collabTheme: "Music",
		rgbBacklit: false,
		hotswap: false,
		switchType: "Cherry MX",
		rappodTrigger: false,
		tags: ["Vintage"],
		price: 139.99,
		model: "Majestouch 2",
		series: "Majestouch",
		stock: 25,
		currency: "USD",
	},
	{
		_id: { $oid: "678fff12b131ed622ef22d88" },
		name: "Keychron Q1 QMK Custom",
		category: "Keyboard",
		brand: "Keychron",
		layout: "75%",
		caseMaterial: "Aluminum",
		collabTheme: "None",
		rgbBacklit: true,
		hotswap: true,
		switchType: "Gateron",
		rappodTrigger: false,
		tags: ["Custom", "Customizable", "RGB Backlit"],
		price: 169.99,
		model: "Q1",
		series: "Q Series",
		stock: 50,
		currency: "USD",
	},
	{
		_id: { $oid: "678fff12b131ed622ef22d89" },
		name: "Ducky One 2 SF Gaming",
		category: "Keyboard",
		brand: "Ducky",
		layout: "65%",
		caseMaterial: "Plastic",
		collabTheme: "Game",
		rgbBacklit: true,
		hotswap: true,
		switchType: "Cherry MX",
		rappodTrigger: false,
		tags: ["Limited Edition", "RGB Backlit"],
		price: 129.99,
		model: "One 2 SF",
		series: "One 2",
		stock: 30,
		currency: "USD",
	},
	{
		_id: { $oid: "678fff12b131ed622ef22d8a" },
		name: "Varmilo Sakura VA87M",
		category: "Keyboard",
		brand: "Varmilo",
		layout: "TKL",
		caseMaterial: "Wood",
		collabTheme: "Anime",
		rgbBacklit: false,
		hotswap: false,
		switchType: "Cherry MX",
		rappodTrigger: false,
		tags: ["Artisan", "Limited Edition"],
		price: 159.99,
		model: "VA87M",
		series: "VA",
		stock: 15,
		currency: "USD",
	},
	{
		_id: { $oid: "678fff12b131ed622ef22d8b" },
		name: "Leopold FC900R PD",
		category: "Keyboard",
		brand: "Leopold",
		layout: "Fullsize",
		caseMaterial: "Plastic",
		collabTheme: "None",
		rgbBacklit: false,
		hotswap: false,
		switchType: "Cherry MX",
		rappodTrigger: false,
		tags: ["Custom", "Vintage"],
		price: 149.99,
		model: "FC900R",
		series: "FC",
		stock: 40,
		currency: "USD",
	},
	{
		_id: { $oid: "678fff12b131ed622ef22d8d" },
		name: "KBDfans Tofu60",
		category: "Keyboard",
		brand: "KBDfans",
		layout: "60%",
		caseMaterial: "Aluminum",
		collabTheme: "None",
		rgbBacklit: true,
		hotswap: true,
		switchType: "Kailh",
		rappodTrigger: false,
		tags: ["Custom", "DIY", "RGB Backlit"],
		price: 179.99,
		model: "Tofu60",
		series: "Tofu",
		stock: 45,
		currency: "USD",
	},
];

const res = new Set(datas.map((data) => {
	const { _id, name, brand, layout, caseMaterial, collabTheme, rgbBacklit, hotswap, switchType, rappodTrigger, tags, price, model, series, stock, currency, src } = data;
	return switchType;
}));

console.log(Array.from(res));